# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expense_manager.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 730)
        MainWindow.setStyleSheet("background-color: rgb(136, 96, 208);\n"
"selection-background-color: rgb(173, 127, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 1161, 671))
        self.tabWidget.setStyleSheet("background-color: rgb(132, 206, 235);\n"
"selection-background-color: rgb(86, 128, 233);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.g3 = QtWidgets.QGraphicsView(self.tab_1)
        self.g3.setGeometry(QtCore.QRect(800, 20, 321, 231))
        self.g3.setStyleSheet("background-color: rgb(193, 200, 228);")
        self.g3.setObjectName("g3")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_1)
        self.graphicsView.setGeometry(QtCore.QRect(20, 350, 581, 281))
        self.graphicsView.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.graphicsView.setObjectName("graphicsView")
        self.Filter_combo = QtWidgets.QComboBox(self.tab_1)
        self.Filter_combo.setGeometry(QtCore.QRect(450, 310, 151, 31))
        self.Filter_combo.setStyleSheet("background-color: rgb(136, 96, 208);")
        self.Filter_combo.setObjectName("Filter_combo")
        self.Filter_combo.addItem("")
        self.Filter_combo.addItem("")
        self.Filter_combo.addItem("")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(400, 310, 41, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(710, 280, 111, 21))
        self.label_2.setObjectName("label_2")
        self.g2 = QtWidgets.QGraphicsView(self.tab_1)
        self.g2.setGeometry(QtCore.QRect(460, 20, 301, 231))
        self.g2.setStyleSheet("background-color: rgb(193, 200, 228);")
        self.g2.setObjectName("g2")
        self.g1 = QtWidgets.QGraphicsView(self.tab_1)
        self.g1.setGeometry(QtCore.QRect(30, 20, 401, 231))
        self.g1.setStyleSheet("background-color: rgb(193, 200, 228);")
        self.g1.setObjectName("g1")
        self.RecentActivity_listview = QtWidgets.QListView(self.tab_1)
        self.RecentActivity_listview.setGeometry(QtCore.QRect(670, 320, 441, 301))
        self.RecentActivity_listview.setStyleSheet("\n"
"background-color: rgb(211, 215, 207);")
        self.RecentActivity_listview.setObjectName("RecentActivity_listview")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 40, 381, 261))
        self.graphicsView_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_3.setGeometry(QtCore.QRect(430, 40, 341, 261))
        self.graphicsView_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 181, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(420, 10, 191, 17))
        self.label_6.setObjectName("label_6")
        self.Filter_combo_2 = QtWidgets.QComboBox(self.tab_2)
        self.Filter_combo_2.setGeometry(QtCore.QRect(600, 10, 181, 21))
        self.Filter_combo_2.setStyleSheet("background-color: rgb(136, 96, 208);")
        self.Filter_combo_2.setObjectName("Filter_combo_2")
        self.Filter_combo_2.addItem("")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 340, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 390, 101, 17))
        self.label_8.setObjectName("label_8")
        self.Filter_combo_3 = QtWidgets.QComboBox(self.tab_2)
        self.Filter_combo_3.setGeometry(QtCore.QRect(140, 390, 181, 21))
        self.Filter_combo_3.setStyleSheet("background-color: rgb(136, 96, 208);")
        self.Filter_combo_3.setObjectName("Filter_combo_3")
        self.Filter_combo_3.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(160, 430, 211, 31))
        self.textEdit.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textEdit.setObjectName("textEdit")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(40, 430, 111, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(40, 510, 111, 20))
        self.label_10.setObjectName("label_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(150, 490, 241, 51))
        self.textEdit_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(960, 580, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_6.setGeometry(QtCore.QRect(790, 40, 341, 261))
        self.graphicsView_6.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_2)
        self.calendarWidget.setGeometry(QtCore.QRect(480, 370, 456, 171))
        self.calendarWidget.setStyleSheet("border-color: rgb(136, 138, 133);\n"
"background-color: rgb(233, 128, 116);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(30, 10, 151, 17))
        self.label_11.setObjectName("label_11")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_4.setGeometry(QtCore.QRect(20, 40, 371, 271))
        self.graphicsView_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(410, 20, 191, 17))
        self.label_12.setObjectName("label_12")
        self.Filter_combo_4 = QtWidgets.QComboBox(self.tab_3)
        self.Filter_combo_4.setGeometry(QtCore.QRect(600, 20, 181, 21))
        self.Filter_combo_4.setStyleSheet("background-color: rgb(136, 96, 208);")
        self.Filter_combo_4.setObjectName("Filter_combo_4")
        self.Filter_combo_4.addItem("")
        self.Filter_combo_4.addItem("")
        self.Filter_combo_4.addItem("")
        self.Filter_combo_4.addItem("")
        self.Filter_combo_4.addItem("")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_5.setGeometry(QtCore.QRect(430, 50, 351, 261))
        self.graphicsView_5.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(30, 360, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(40, 410, 101, 17))
        self.label_14.setObjectName("label_14")
        self.Filter_combo_5 = QtWidgets.QComboBox(self.tab_3)
        self.Filter_combo_5.setGeometry(QtCore.QRect(140, 410, 181, 21))
        self.Filter_combo_5.setStyleSheet("background-color: rgb(136, 96, 208);")
        self.Filter_combo_5.setObjectName("Filter_combo_5")
        self.Filter_combo_5.addItem("")
        self.Filter_combo_5.addItem("")
        self.Filter_combo_5.addItem("")
        self.Filter_combo_5.addItem("")
        self.Filter_combo_5.addItem("")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(30, 460, 111, 20))
        self.label_15.setObjectName("label_15")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(150, 460, 211, 31))
        self.textEdit_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(30, 530, 111, 20))
        self.label_16.setObjectName("label_16")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_4.setGeometry(QtCore.QRect(140, 510, 241, 51))
        self.textEdit_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(980, 570, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_7.setGeometry(QtCore.QRect(800, 50, 341, 261))
        self.graphicsView_7.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.tab_3)
        self.calendarWidget_2.setGeometry(QtCore.QRect(440, 390, 456, 171))
        self.calendarWidget_2.setStyleSheet("border-color: rgb(136, 138, 133);\n"
"background-color: rgb(233, 128, 116);")
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 51, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 10, 221, 21))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.g1)
        MainWindow.setTabOrder(self.g1, self.g2)
        MainWindow.setTabOrder(self.g2, self.g3)
        MainWindow.setTabOrder(self.g3, self.graphicsView)
        MainWindow.setTabOrder(self.graphicsView, self.Filter_combo)
        MainWindow.setTabOrder(self.Filter_combo, self.RecentActivity_listview)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>OverView</p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>OverView</p></body></html>"))
        self.Filter_combo.setItemText(0, _translate("MainWindow", "Daily"))
        self.Filter_combo.setItemText(1, _translate("MainWindow", "Monthly"))
        self.Filter_combo.setItemText(2, _translate("MainWindow", "Yearly"))
        self.label.setText(_translate("MainWindow", "Filter:"))
        self.label_2.setText(_translate("MainWindow", "Recent Activity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "OverView"))
        self.label_5.setText(_translate("MainWindow", "timewise income graph"))
        self.label_6.setText(_translate("MainWindow", "category wise time  graph"))
        self.Filter_combo_2.setItemText(0, _translate("MainWindow", "Eneterd income type"))
        self.label_7.setText(_translate("MainWindow", "Enter New Expense"))
        self.label_8.setText(_translate("MainWindow", "Income Type:"))
        self.Filter_combo_3.setItemText(0, _translate("MainWindow", "Eneterd expense type"))
        self.label_9.setText(_translate("MainWindow", "or write ur own"))
        self.label_10.setText(_translate("MainWindow", "Enter Amount:"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Income"))
        self.label_11.setText(_translate("MainWindow", "all expense graph"))
        self.label_12.setText(_translate("MainWindow", "category wise time  graph"))
        self.Filter_combo_4.setItemText(0, _translate("MainWindow", "Eneterd income type"))
        self.Filter_combo_4.setItemText(1, _translate("MainWindow", "food"))
        self.Filter_combo_4.setItemText(2, _translate("MainWindow", "Travel"))
        self.Filter_combo_4.setItemText(3, _translate("MainWindow", "Education"))
        self.Filter_combo_4.setItemText(4, _translate("MainWindow", "Investment"))
        self.label_13.setText(_translate("MainWindow", "Enter New Income "))
        self.label_14.setText(_translate("MainWindow", "Income Type:"))
        self.Filter_combo_5.setItemText(0, _translate("MainWindow", "Eneterd expense type"))
        self.Filter_combo_5.setItemText(1, _translate("MainWindow", "food"))
        self.Filter_combo_5.setItemText(2, _translate("MainWindow", "Travel"))
        self.Filter_combo_5.setItemText(3, _translate("MainWindow", "Education"))
        self.Filter_combo_5.setItemText(4, _translate("MainWindow", "Investment"))
        self.label_15.setText(_translate("MainWindow", "or write ur own"))
        self.label_16.setText(_translate("MainWindow", "Enter Amount:"))
        self.pushButton_2.setText(_translate("MainWindow", "Enter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Expense"))
        self.label_3.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "Name will be Displayed HERE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

